### ISSUE TITLE
Jwt token undefined after page refresh

### ISSUE THREAD

**Issue by VladislavAntonyuk** [VahidN/ASPNETCore2JwtAuthentication#2]
Request URL:http://localhost:5000/api/MyProtectedApi
Request Method:GET
Status Code:401 Unauthorized
Remote Address:[::1]:5000
Referrer Policy:no-referrer-when-downgrade
Response Headers
view source
Content-Type:text/plain
Date:Fri, 02 Feb 2018 21:53:39 GMT
Server:Kestrel
Transfer-Encoding:chunked
WWW-Authenticate:Bearer error="invalid_token"
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, br
Accept-Language:en-US,en;q=0.9
Authorization:Bearer undefined
Connection:keep-alive
Host:localhost:5000
Referer:http://localhost:5000/
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36
X-Requested-With:XMLHttpRequest

**Comment by VahidN** [comment]
It's true. Because I'm not using the [window.localStorage](https://github.com/VahidN/ASPNETCore2JwtAuthentication/blob/master/src/ASPNETCore2JwtAuthentication.AngularClient/src/app/core/services/browser-storage.service.ts) to store it for this simple demo. If you are looking for a good client implantation, try the [AngularClient](https://github.com/VahidN/ASPNETCore2JwtAuthentication/tree/master/src/ASPNETCore2JwtAuthentication.AngularClient) of this project.

**Comment by VladislavAntonyuk** [comment]
is it a secure place to save token for cross-pages in localStorage. Or it is better to save it somewhere else like save in file via File.WriteAllText() in Contoller?

**Comment by VahidN** [comment]
Client-side storage includes `session storage`, `local storage`, `File Storage` ،`WebSQL` ،`IndexedDB` and `cookie` storage. `Jwt token undefined after page refresh` means you want to implement the client side `remember me` option. So you need to use one of mentioned options. If you want to limit the life time of the storage to the end of the session, use `session storage`, otherwise using `local storage` is a preferred choice here with JWTs.
